name: feature_h
publish_to: none
resolution: workspace
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  core_library_2:
    path: ../../core/core_library_2

dev_dependencies:
  test: ^1.26.0
